# This is a basic workflow that is manually triggered

name: Manual workflow
permissions:
  contents: write
on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v5
    - name: add upstream
      run: git remote add upstream https://github.com/zigbee2mqtt/hassio-zigbee2mqtt
    - name: run script
      run: ./update.sh
