# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v5
    - name: add upstream
      run: git remote add upstream https://github.com/zigbee2mqtt/hassio-zigbee2mqtt
    - name: list remotes
      run: git remote -v
    - name: Check PWD
      run: cat update.sh
    - name: List
      run: ls
